// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU1hMTSjbG4vL9JhJRlj-5QVrSAASuk9Q',
    appId: '1:144079572703:web:0002aa0e2825073825a36a',
    messagingSenderId: '144079572703',
    projectId: 'fir-lightenexnv',
    authDomain: 'fir-lightenexnv.firebaseapp.com',
    storageBucket: 'fir-lightenexnv.firebasestorage.app',
    measurementId: 'G-8Y5KYRBX9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBExrjaGXer5WZcVkKqKYctvOiWCL6M39w',
    appId: '1:144079572703:android:86eec478476a022025a36a',
    messagingSenderId: '144079572703',
    projectId: 'fir-lightenexnv',
    storageBucket: 'fir-lightenexnv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihzKQ0IncbqdSQo8AI_9Stdf6rhLXDE8',
    appId: '1:144079572703:ios:f5b4f96d1f7e7a8925a36a',
    messagingSenderId: '144079572703',
    projectId: 'fir-lightenexnv',
    storageBucket: 'fir-lightenexnv.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihzKQ0IncbqdSQo8AI_9Stdf6rhLXDE8',
    appId: '1:144079572703:ios:94e396c0bc1269e725a36a',
    messagingSenderId: '144079572703',
    projectId: 'fir-lightenexnv',
    storageBucket: 'fir-lightenexnv.firebasestorage.app',
    iosBundleId: 'com.news.lightenex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU1hMTSjbG4vL9JhJRlj-5QVrSAASuk9Q',
    appId: '1:144079572703:web:2b389049bfed514a25a36a',
    messagingSenderId: '144079572703',
    projectId: 'fir-lightenexnv',
    authDomain: 'fir-lightenexnv.firebaseapp.com',
    storageBucket: 'fir-lightenexnv.firebasestorage.app',
    measurementId: 'G-QKL25D89M4',
  );
}
